---
- name: cluster | check if hosts are in clustered
  shell: >-
    mongosh --port {{ mongo_net.port }} --quiet --eval 'db.isMaster().hosts'
  register: check_cluster
  changed_when: false
  retries: 3
  delay: 3
  until: check_cluster.rc == 0

- name: cluster | set fact
  set_fact:
    check_cluster: "{{ check_cluster.stdout }}"

- name: cluster | build member list
  set_fact:
    members: >-
      {{
        members | default([]) +
        [{
          '_id': hostid,
          'host': hostvars[item].ansible_host + ':{{ mongo_net.port }}',
          'priority': hostvars[item].mongo_replication_weight,
          'hidden': hostvars[item].mongo_replication_is_hidden 
        }]
      }}
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    index_var: hostid
  run_once: true

- name: cluster | build bson members list
  set_fact:
    members_bson: >- 
      { _id : "{{ mongo_replication.replSetName }}", members :  {{ members | to_json }} }

- name: cluster | block to initial build the replica set
  block:

  - name: cluster | set fact for arbiter index number
    set_fact:
      arbiter_index: "{{ hostid }}"
    when: hostvars[item].mongo_replication_is_arbiter
    loop: "{{ ansible_play_hosts }}"
    loop_control:
      index_var: hostid

  - name: cluster | initial build
    community.mongodb.mongodb_replicaset:
      login_host: localhost
      login_port: "{{ mongo_net.port }}"
      login_user: admin
      login_password: "{{ mongo_admin_pass }}"
      replica_set: "{{ mongo_replication.replSetName }}"
      members: "{{ members }}"
      arbiter_at_index: "{{ arbiter_index | default(omit) }}"
      validate: false
    when: check_cluster | length == 0
    register: initial_build_status
    ignore_errors: yes 

  - name: cluster | reserve initial build
    shell: >-
      mongosh -u admin -p {{ mongo_admin_pass }} --port {{ mongo_net.port }} --eval 'rs.initiate({{ members_bson }})'
    when: check_cluster | length == 0 and initial_build_status.failed

  - name: cluster | reconfigure replicaset
    community.mongodb.mongodb_replicaset:
      login_host: localhost
      login_port: "{{ mongo_net.port }}"
      login_user: admin
      login_password: "{{ mongo_admin_pass }}"
      replica_set: "{{ mongo_replication.replSetName }}"
      members: "{{ members }}"
      arbiter_at_index: "{{ arbiter_index | default(omit) }}"
      reconfigure: true
      validate: false
    when: check_cluster | length > 0

  - name: cluster | wait until cluster health is ok
    community.mongodb.mongodb_status:
      login_host: localhost
      login_user: admin
      login_password: "{{ mongo_admin_pass }}"
      login_port: "{{ mongo_net.port }}"
      validate: minimal
      poll: 5
      interval: 12
      replica_set: "{{ mongo_replication.replSetName }}"

  - name: cluster | place original config
    template:
      src: mongod.conf.j2
      dest: /etc/mongod.conf
      owner: root
      group: root
      mode: 0644

  - name: cluster | restart mongod service one by one
    shell: systemctl restart mongod && sleep 15
    run_once: true
    delegate_to: "{{ item }}"
    loop: "{{ ansible_play_hosts }}"
    when: not mongo_setup_container

  - name: cluster | restart mongod service one by one
    community.docker.docker_container:
      name: "{{ mongo_container_name }}"
      state: started
      restart: true
    run_once: true
    delegate_to: "{{ item }}"
    loop: "{{ ansible_play_hosts }}"
    when: mongo_setup_container

  - name: cluster | wait until cluster health is ok
    community.mongodb.mongodb_status:
      login_host: localhost
      login_port: "{{ mongo_net.port }}"
      login_user: admin
      login_password: "{{ mongo_admin_pass }}"
      validate: minimal
      poll: 5
      interval: 12
      replica_set: "{{ mongo_replication.replSetName }}"

  run_once: true
